import "./globals.css"

import type { Metadata } from "next"
import { Geist, Geist_Mono, Unbounded, Inter } from "next/font/google"
import Navigation from "@/components/Navigation"
import Footer from "@/components/Footer"
import ChunkErrorReload from "@/components/chunk-error-reload"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

const unbounded = Unbounded({
  variable: "--font-unbounded",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"]
})

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Cool Macaly App",
  description: "Generated by Macaly",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${unbounded.variable} ${inter.variable} antialiased`}
        >
          <ChunkErrorReload />
          <Navigation />
          <main className="pt-16">
            {children}
          </main>
          <Footer />
        </body>
    </html>
  )
}





